### ISSUE TITLE
Contribute solutions of HackerRank Problems

### ISSUE THREAD

**Issue by Arejay23** [Arejay23/Hackerrank#3]
### Description
This repo contains solutions of various HackerRank problems.
Contribute Solutions that are better than already present or which are not present.
Refer to contributing guidelines in README.md.

# It can have multiple assignees.

**Comment by rishavk1102** [comment]
Hi, please assign this to me. I am interested.

**Comment by Arejay23** [comment]
@rishavk1102  go ahead.
Please contribute according to contributing guidelines.
