### ISSUE TITLE
Better if someone write the questions too?

### ISSUE THREAD

**Issue by AshAman999** [Arejay23/Hackerrank#4]

**Comment by Arejay23** [comment]
@AshAman999 What issue are you proposing?
Please describe.
Questions are available on hacker rank

**Comment by AshAman999** [comment]
I thought it would be better if one can access it from here too, like linking the questions in a readme.md for every question, just thought it would be helpful.....
SORRY if it bothered you

**Comment by Arejay23** [comment]
It will be lot of work and a lot of writing for each code.
If you want to create readme for each question you can.
